server:
  port: 80

logging:
  config: classpath:logback-spring.xml

wechat:
  token: atming_

keyword:
  versionLocation: data/keyword_version.txt
  messageLocation: data/keyword.json

openai:
  keyList:
    - "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"
    - "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"
